sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "4"
    - node_js: "0.10"
    - node_js: "0.12"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
addons:
  ssh_known_hosts: kbve.com
before_install:
- openssl aes-256-cbc -K $encrypted_60d801ad527c_key -iv $encrypted_60d801ad527c_iv
  -in kbve_api.enc -out kbve_api -d
after_success:
  - bash deploy.sh
